# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog of MarWe
email: marweblog.20.mweis@spamgourmet.com
description: > # this means to ignore newlines until "baseurl:"
        This is my personal blog about miscellaneous topics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.machen.click/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  MarWe

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
